
# travis phases and our setup
# before_install
# install                           -- install dependencies
# before_script
# script                            -- build the site, do htmlproofer
# after_success
# after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script

sudo: false

language: ruby

rvm:
- 2.3.1

install:
- bundle install
  
script:
- bundle exec jekyll build
- bundle exec htmlproofer _site --assume-extension --check-html

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
