
# general
title: Data Linkage Repository
email: ozgurakgun+dlrep@gmail.com
description: Data Linkage Repository
baseurl: ""
url: "http://dlrep.github.io"                   # we need a custom domain!
# twitter_username: ?
github_username: dlrep

# build settings
layouts_dir: __internal/layouts
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: __internal/sass
  style: :compressed

exclude:
- Gemfile
- Gemfile.lock
- vendor

# collections
collections:
- custom
- datasets
- tasks
- tags

collections:
  custom:
    output: true
  datasets:
    output: true
    permalink: /dataset/:path
  tasks:
    output: true
    permalink: /task/:path
  tags:
    output: true
    permalink: /tag/:path

defaults:
  - scope:
      type: custom
    values:
      layout: custom
  - scope:
      type: datasets
    values:
      layout: dataset
  - scope:
      type: tasks
    values:
      layout: task
  - scope:
      type: tags
    values:
      layout: tag
